// frontend/src/components/views/MatrixView.svelte
<script lang="ts">
  import { settingsStore } from '@/stores/settings';
  import { Calendar, Clock, AlertCircle, ArrowRight, UserCheck, Trash } from '@lucide/svelte';
  import type { Task } from '@/types';
  import { useI18n } from '@/composables/useI18n';

  let {
    tasks = [],
    ontaskclick
  } = $props<{
    tasks: Task[];
    ontaskclick?: (task: Task) => void;
  }>();

  const { t } = useI18n();

  const updateThreshold = (val: number) => {
    if (val < 1) val = 1;
    settingsStore.setThresholdDays(val);
  };

  const isUrgent = (task: Task): boolean => {
    if (!task.due_date) return false;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const dueDate = new Date(task.due_date);
    dueDate.setHours(0, 0, 0, 0);
    const diffTime = dueDate.getTime() - today.getTime();
    const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
    return diffDays <= settingsStore.thresholdDays;
  };

  const isPrioritized = (task: Task): boolean => {
    return task.priority === 'high' || task.priority === 'urgent';
  };

  const quadrants = $derived.by(() => {
    const q1: Task[] = [];
    const q2: Task[] = [];
    const q3: Task[] = [];
    const q4: Task[] = [];

    tasks.forEach((task) => {
      if (task.bucket === 'done') return;

      const urg = isUrgent(task);
      const prio = isPrioritized(task);

      if (urg && prio) q1.push(task);
      else if (!urg && prio) q2.push(task);
      else if (urg && !prio) q3.push(task);
      else q4.push(task);
    });

    return { q1, q2, q3, q4 };
  });

  const getPriorityClasses = (prio: string) => {
    switch (prio) {
      case 'low':
        return 'bg-blue-500/10 text-blue-400 border-blue-500/20';
      case 'medium':
        return 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20';
      case 'high':
        return 'bg-orange-500/10 text-orange-400 border-orange-500/20';
      case 'urgent':
        return 'bg-red-500/10 text-red-400 border-red-500/20 animate-pulse';
      default:
        return 'bg-slate-500/10 text-slate-400 border-slate-500/20';
    }
  };

  const formatDate = (dateStr: string) => {
    try {
      const d = new Date(dateStr);
      return d.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
    } catch {
      return dateStr;
    }
  };
</script>

<div class="flex flex-col h-full overflow-hidden select-none w-full gap-3.5">
  <!-- Adjust Threshold Controls -->
  <div class="flex items-center justify-between bg-theme-card/35 border border-theme-border/60 rounded px-4 py-2.5 shrink-0">
    <div class="flex items-center gap-2 text-sm font-semibold text-theme-text-card">
      <Clock class="w-4 h-4 text-theme-accent" />
      <span>{t('matrix.thresholdLabel', { days: settingsStore.thresholdDays })}</span>
    </div>
    <div class="flex items-center gap-1.5">
      <button
        onclick={() => updateThreshold(settingsStore.thresholdDays - 1)}
        class="w-6 h-6 flex items-center justify-center bg-theme-card border border-theme-border rounded hover:bg-theme-column/80 text-theme-text-card text-xs font-bold cursor-pointer transition-colors"
        disabled={settingsStore.thresholdDays <= 1}
      >
        -
      </button>
      <input
        type="number"
        value={settingsStore.thresholdDays}
        onchange={(e) => updateThreshold(Number((e.target as HTMLInputElement).value))}
        min="1"
        class="w-12 text-center bg-theme-base/60 border border-theme-border rounded py-0.5 text-xs font-bold text-theme-text-input focus:outline-none focus:border-theme-primary"
      />
      <button
        onclick={() => updateThreshold(settingsStore.thresholdDays + 1)}
        class="w-6 h-6 flex items-center justify-center bg-theme-card border border-theme-border rounded hover:bg-theme-column/80 text-theme-text-card text-xs font-bold cursor-pointer transition-colors"
      >
        +
      </button>
    </div>
  </div>

  <!-- 2x2 Matrix Grid -->
  <div class="flex-grow grid grid-cols-1 md:grid-cols-2 gap-3.5 min-h-0 overflow-y-auto md:overflow-hidden p-0.5">
    <!-- Q1: Urgent & Important -->
    <div class="flex flex-col bg-theme-column/40 border border-theme-border rounded h-full min-h-[220px] overflow-hidden md:h-full">
      <div class="px-3.5 py-2.5 border-b border-theme-border bg-red-500/5 flex items-center gap-2 shrink-0">
        <AlertCircle class="w-4.5 h-4.5 text-red-400 shrink-0" />
        <div class="min-w-0">
          <h4 class="font-bold text-sm uppercase tracking-wider text-red-400 truncate">{t('matrix.q1Title')}</h4>
          <p class="text-xs text-theme-text-muted leading-tight truncate">{t('matrix.q1Desc')}</p>
        </div>
        <span class="ml-auto px-2 py-0.25 bg-red-500/10 border border-red-500/20 text-red-400 text-xs font-bold rounded">
          {quadrants.q1.length}
        </span>
      </div>
      <div class="flex-grow p-3 overflow-y-auto space-y-2 scroller-thin">
        {#if !quadrants.q1.length}
          <div class="h-full flex items-center justify-center text-theme-text-muted italic text-xs">
            {t('matrix.emptyQuadrant')}
          </div>
        {:else}
          {#each quadrants.q1 as task (task.id)}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div
              onclick={() => ontaskclick?.(task)}
              class="bg-theme-card border border-theme-border/60 hover:border-red-500/40 p-2.5 rounded shadow-sm hover:shadow-theme-ring transition-all duration-150 cursor-pointer flex flex-col gap-1.5"
            >
              <div class="flex justify-between items-start gap-2">
                <span class="text-sm text-theme-text-card line-clamp-2 leading-tight">{task.title}</span>
              </div>
              <div class="flex items-center gap-2 mt-0.5 text-xs">
                {#if task.due_date}
                  <span class="flex items-center gap-1 text-red-400 font-medium">
                    <Calendar class="w-3 h-3" />
                    <span>{formatDate(task.due_date)}</span>
                  </span>
                {/if}
                {#if task.priority}
                  <span
                    class="px-1.5 py-0.25 rounded border text-[10px] font-extrabold uppercase {getPriorityClasses(task.priority)}"
                  >
                    {task.priority}
                  </span>
                {/if}
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </div>

    <!-- Q2: Important & Not Urgent -->
    <div class="flex flex-col bg-theme-column/40 border border-theme-border rounded h-full min-h-[220px] overflow-hidden md:h-full">
      <div class="px-3.5 py-2.5 border-b border-theme-border bg-blue-500/5 flex items-center gap-2 shrink-0">
        <ArrowRight class="w-4.5 h-4.5 text-blue-400 shrink-0" />
        <div class="min-w-0">
          <h4 class="font-bold text-sm uppercase tracking-wider text-blue-400 truncate">{t('matrix.q2Title')}</h4>
          <p class="text-xs text-theme-text-muted leading-tight truncate">{t('matrix.q2Desc')}</p>
        </div>
        <span class="ml-auto px-2 py-0.25 bg-blue-500/10 border border-blue-500/20 text-blue-400 text-xs font-bold rounded">
          {quadrants.q2.length}
        </span>
      </div>
      <div class="flex-grow p-3 overflow-y-auto space-y-2 scroller-thin">
        {#if !quadrants.q2.length}
          <div class="h-full flex items-center justify-center text-theme-text-muted italic text-xs">
            {t('matrix.emptyQuadrant')}
          </div>
        {:else}
          {#each quadrants.q2 as task (task.id)}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div
              onclick={() => ontaskclick?.(task)}
              class="bg-theme-card border border-theme-border/60 hover:border-blue-500/40 p-2.5 rounded shadow-sm hover:shadow-theme-ring transition-all duration-150 cursor-pointer flex flex-col gap-1.5"
            >
              <div class="flex justify-between items-start gap-2">
                <span class="text-sm text-theme-text-card line-clamp-2 leading-tight">{task.title}</span>
              </div>
              <div class="flex items-center gap-2 mt-0.5 text-xs">
                {#if task.due_date}
                  <span class="flex items-center gap-1 text-theme-text-muted">
                    <Calendar class="w-3 h-3" />
                    <span>{formatDate(task.due_date)}</span>
                  </span>
                {/if}
                {#if task.priority}
                  <span
                    class="px-1.5 py-0.25 rounded border text-[10px] font-extrabold uppercase {getPriorityClasses(task.priority)}"
                  >
                    {task.priority}
                  </span>
                {/if}
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </div>

    <!-- Q3: Urgent & Not Important -->
    <div class="flex flex-col bg-theme-column/40 border border-theme-border rounded h-full min-h-[220px] overflow-hidden md:h-full">
      <div class="px-3.5 py-2.5 border-b border-theme-border bg-orange-500/5 flex items-center gap-2 shrink-0">
        <UserCheck class="w-4.5 h-4.5 text-orange-400 shrink-0" />
        <div class="min-w-0">
          <h4 class="font-bold text-sm uppercase tracking-wider text-orange-400 truncate">{t('matrix.q3Title')}</h4>
          <p class="text-xs text-theme-text-muted leading-tight truncate">{t('matrix.q3Desc')}</p>
        </div>
        <span class="ml-auto px-2 py-0.25 bg-orange-500/10 border border-orange-500/20 text-orange-400 text-xs font-bold rounded">
          {quadrants.q3.length}
        </span>
      </div>
      <div class="flex-grow p-3 overflow-y-auto space-y-2 scroller-thin">
        {#if !quadrants.q3.length}
          <div class="h-full flex items-center justify-center text-theme-text-muted italic text-xs">
            {t('matrix.emptyQuadrant')}
          </div>
        {:else}
          {#each quadrants.q3 as task (task.id)}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div
              onclick={() => ontaskclick?.(task)}
              class="bg-theme-card border border-theme-border/60 hover:border-orange-500/40 p-2.5 rounded shadow-sm hover:shadow-theme-ring transition-all duration-150 cursor-pointer flex flex-col gap-1.5"
            >
              <div class="flex justify-between items-start gap-2">
                <span class="text-sm text-theme-text-card line-clamp-2 leading-tight">{task.title}</span>
              </div>
              <div class="flex items-center gap-2 mt-0.5 text-xs">
                {#if task.due_date}
                  <span class="flex items-center gap-1 text-red-400 font-medium">
                    <Calendar class="w-3 h-3" />
                    <span>{formatDate(task.due_date)}</span>
                  </span>
                {/if}
                {#if task.priority}
                  <span
                    class="px-1.5 py-0.25 rounded border text-[10px] font-extrabold uppercase {getPriorityClasses(task.priority)}"
                  >
                    {task.priority}
                  </span>
                {/if}
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </div>

    <!-- Q4: Not Urgent & Not Important -->
    <div class="flex flex-col bg-theme-column/40 border border-theme-border rounded h-full min-h-[220px] overflow-hidden md:h-full">
      <div class="px-3.5 py-2.5 border-b border-theme-border bg-slate-500/5 flex items-center gap-2 shrink-0">
        <Trash class="w-4.5 h-4.5 text-slate-400 shrink-0" />
        <div class="min-w-0">
          <h4 class="font-bold text-sm uppercase tracking-wider text-slate-400 truncate">{t('matrix.q4Title')}</h4>
          <p class="text-xs text-theme-text-muted leading-tight truncate">{t('matrix.q4Desc')}</p>
        </div>
        <span class="ml-auto px-2 py-0.25 bg-slate-500/10 border border-slate-500/20 text-slate-400 text-xs font-bold rounded">
          {quadrants.q4.length}
        </span>
      </div>
      <div class="flex-grow p-3 overflow-y-auto space-y-2 scroller-thin">
        {#if !quadrants.q4.length}
          <div class="h-full flex items-center justify-center text-theme-text-muted italic text-xs">
            {t('matrix.emptyQuadrant')}
          </div>
        {:else}
          {#each quadrants.q4 as task (task.id)}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div
              onclick={() => ontaskclick?.(task)}
              class="bg-theme-card border border-theme-border/60 hover:border-slate-500/40 p-2.5 rounded shadow-sm hover:shadow-theme-ring transition-all duration-150 cursor-pointer flex flex-col gap-1.5"
            >
              <div class="flex justify-between items-start gap-2">
                <span class="text-sm text-theme-text-card line-clamp-2 leading-tight">{task.title}</span>
              </div>
              <div class="flex items-center gap-2 mt-0.5 text-xs">
                {#if task.due_date}
                  <span class="flex items-center gap-1 text-theme-text-muted">
                    <Calendar class="w-3 h-3" />
                    <span>{formatDate(task.due_date)}</span>
                  </span>
                {/if}
                {#if task.priority}
                  <span
                    class="px-1.5 py-0.25 rounded border text-[10px] font-extrabold uppercase {getPriorityClasses(task.priority)}"
                  >
                    {task.priority}
                  </span>
                {/if}
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </div>
  </div>
</div>

// web/src/components/views/MatrixView.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import { useEventListener } from '@vueuse/core';
import { useRoute } from 'vue-router';
import { storeToRefs } from 'pinia';
import { useSettingsStore } from '@/stores/settings';
import { useProjectStore } from '@/stores/project';
import { useUiStore } from '@/stores/ui';
import { AlertCircle, ArrowRight, UserCheck, Trash, MoreHorizontal, List, LayoutGrid, Grid } from '@lucide/vue';
import type { Task } from '@/types';
import GenericColumn from '@/components/ui/GenericColumn.vue';
import { useI18n } from '@/composables/useI18n';
import { updateTask } from '@/api';

const { t } = useI18n();

const props = defineProps<{
  tasks: Task[];
}>();

import { useSelectionStore } from '@/stores/selection';
const selectionStore = useSelectionStore();

const emit = defineEmits<{
  (e: 'toggle-select', task: Task): void;
}>();

const route = useRoute();
const settingsStore = useSettingsStore();
const projectStore = useProjectStore();
const uiStore = useUiStore();
const activeProjectId = computed(() => (route.params.projectId as string) || '');
const { thresholdDays, hideDoneColumn, hideArchiveColumn } = storeToRefs(settingsStore);

const fetchViewTasks = async () => {
  if (!activeProjectId.value) return;
  await projectStore.fetchTasks({
    projectId: activeProjectId.value,
  });
};

onMounted(async () => {
  await fetchViewTasks();
});

watch([activeProjectId, hideDoneColumn, hideArchiveColumn], async () => {
  await fetchViewTasks();
});

const updateThreshold = (val: number) => {
  if (val < 1) val = 1;
  settingsStore.setThresholdDays(val);
};

// Check if task is urgent
const isUrgent = (task: Task): boolean => {
  if (!task.due_date) return false;
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const dueDate = new Date(task.due_date);
  dueDate.setHours(0, 0, 0, 0);
  const diffTime = dueDate.getTime() - today.getTime();
  const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
  return diffDays <= thresholdDays.value;
};

// Check if task is prioritized (Important)
const isPrioritized = (task: Task): boolean => {
  return task.priority === 'high' || task.priority === 'urgent';
};

// Quadrants definition
const quadrants = computed(() => {
  const q1: Task[] = [];
  const q2: Task[] = [];
  const q3: Task[] = [];
  const q4: Task[] = [];

  props.tasks.forEach((task) => {
    // Exclude completed or archived tasks
    if (task.bucket === 'done' || task.bucket === 'archive') return;

    const urgent = isUrgent(task);
    const important = isPrioritized(task);

    if (urgent && important) q1.push(task);
    else if (!urgent && important) q2.push(task);
    else if (urgent && !important) q3.push(task);
    else q4.push(task);
  });

  return { q1, q2, q3, q4 };
});

const activeMenuColId = ref<string | null>(null);

const toggleMenu = (colId: string) => {
  activeMenuColId.value = activeMenuColId.value === colId ? null : colId;
};

const closeMenu = () => {
  activeMenuColId.value = null;
};

useEventListener(window, 'click', closeMenu);

const matrixColumns = computed(() => [
  {
    id: 'q1',
    title: t('matrix.q1Title'),
    subtitle: t('matrix.q1Desc'),
    tasks: quadrants.value.q1,
    color: 'red',
    icon: AlertCircle,
  },
  {
    id: 'q2',
    title: t('matrix.q2Title'),
    subtitle: t('matrix.q2Desc'),
    tasks: quadrants.value.q2,
    color: 'green',
    icon: ArrowRight,
  },
  {
    id: 'q3',
    title: t('matrix.q3Title'),
    subtitle: t('matrix.q3Desc'),
    tasks: quadrants.value.q3,
    color: 'orange',
    icon: UserCheck,
  },
  {
    id: 'q4',
    title: t('matrix.q4Title'),
    subtitle: t('matrix.q4Desc'),
    tasks: quadrants.value.q4,
    color: 'slate',
    icon: Trash,
  },
]);

const handleCardDropped = async (payload: { taskId: string; toId: string }) => {
  const isSelectedTask = selectionStore.isSelected(payload.taskId);
  const tasksToUpdate = isSelectedTask
    ? props.tasks.filter((t) => selectionStore.isSelected(t.id))
    : props.tasks.filter((t) => t.id === payload.taskId);

  if (tasksToUpdate.length === 0) return;

  const today = new Date();
  const todayStr = today.toISOString().split('T')[0];

  // Store original states for potential rollback
  const originalStates = tasksToUpdate.map((t) => ({
    task: t,
    priority: t.priority,
    dueDate: t.due_date,
  }));

  // Optimistically update and call API in parallel
  tasksToUpdate.forEach((t) => {
    let newPriority = t.priority;
    let newDueDate = t.due_date;

    if (payload.toId === 'q1') {
      if (t.priority !== 'high' && t.priority !== 'urgent') {
        newPriority = 'high';
      }
      if (!isUrgent(t)) {
        newDueDate = todayStr;
      }
    } else if (payload.toId === 'q2') {
      if (t.priority !== 'high' && t.priority !== 'urgent') {
        newPriority = 'high';
      }
      if (isUrgent(t)) {
        newDueDate = '';
      }
    } else if (payload.toId === 'q3') {
      if (t.priority === 'high' || t.priority === 'urgent') {
        newPriority = 'medium';
      }
      if (!isUrgent(t)) {
        newDueDate = todayStr;
      }
    } else if (payload.toId === 'q4') {
      if (t.priority === 'high' || t.priority === 'urgent') {
        newPriority = 'medium';
      }
      if (isUrgent(t)) {
        newDueDate = '';
      }
    }

    t.priority = newPriority;
    t.due_date = newDueDate;
  });

  try {
    await Promise.all(
      tasksToUpdate.map((t) =>
        updateTask(t.project_id || activeProjectId.value, t.id, {
          priority: t.priority,
          due_date: t.due_date,
        })
      )
    );
    await fetchViewTasks();
  } catch {
    // Revert all on failure
    originalStates.forEach(({ task, priority, dueDate }) => {
      task.priority = priority;
      task.due_date = dueDate;
    });
  }
};

const sliderPercentage = computed(() => {
  const min = 1;
  const max = 30;
  return ((thresholdDays.value - min) / (max - min)) * 100;
});
</script>

<template>
  <div class="h-full flex flex-col space-y-4">
    <!-- Header with Threshold Slider -->
    <div class="flex items-center justify-between px-1">
      <div class="flex flex-col">
        <h2 class="text-lg font-bold text-theme-text-main flex items-baseline gap-2">
          <span class="w-2 h-2 rounded-full bg-theme-accent"></span>
          {{ t('views.matrix') }}
          <span class="text-xs font-normal text-theme-text-muted ml-2 uppercase tracking-widest">{{ t('views.matrixDesc') }}</span>
        </h2>
      </div>

      <div
        class="flex flex-col items-end gap-1 bg-theme-column/30 border border-theme-border/25 rounded-xl px-4 py-2 hover:bg-theme-column/45 transition-all duration-300 shadow-sm max-w-fit"
      >
        <label class="text-[10px] font-extrabold uppercase tracking-wider text-theme-text-muted select-none leading-none">
          {{ t('matrix.thresholdLabel', { days: thresholdDays }) }}
        </label>
        <div class="relative flex flex-col w-48 mt-1.5">
          <input
            type="range"
            min="1"
            max="30"
            :value="thresholdDays"
            @input="updateThreshold(parseInt(($event.target as HTMLInputElement).value))"
            class="urgency-slider w-full h-1 appearance-none cursor-pointer rounded-full outline-none transition-all duration-150"
            :style="{
              background: `linear-gradient(to right, var(--theme-accent) ${sliderPercentage}%, var(--theme-border) ${sliderPercentage}%)`,
            }"
          />
          <!-- Helper presets / ticks -->
          <div class="flex justify-between w-full px-0.5 mt-1 text-[8px] font-black text-theme-text-muted/60 select-none">
            <span class="cursor-pointer hover:text-theme-accent transition-colors duration-150" @click="updateThreshold(1)">1d</span>
            <span class="cursor-pointer hover:text-theme-accent transition-colors duration-150" @click="updateThreshold(7)">7d</span>
            <span class="cursor-pointer hover:text-theme-accent transition-colors duration-150" @click="updateThreshold(14)">14d</span>
            <span class="cursor-pointer hover:text-theme-accent transition-colors duration-150" @click="updateThreshold(30)">30d</span>
          </div>
        </div>
      </div>
    </div>

    <!-- 2x2 Grid using GenericColumn component -->
    <div class="flex-grow grid grid-cols-1 md:grid-cols-2 gap-4 pb-4 overflow-hidden select-none">
      <GenericColumn
        v-for="col in matrixColumns"
        :key="col.id"
        :id="col.id"
        :title="col.title"
        :tasks="col.tasks"
        :color="col.color"
        :group-name="'matrix-view'"
        :compact-cards="true"
        :is-fluid="true"
        :layout="uiStore.getVirtualColumnLayout('matrix-view', col.id, 'grid-3')"
        @card-dropped="handleCardDropped"
        @toggle-select="(task) => emit('toggle-select', task)"
      >
        <template #header="{ classes }">
          <div
            class="px-3.5 py-2 flex justify-between items-center border-b rounded-t shrink-0 min-h-[48px] cursor-grab active:cursor-grabbing column-drag-handle"
            :class="[classes.bg, classes.border]"
          >
            <!-- Title, Description & Count Badge -->
            <div class="flex items-center gap-2 min-w-0 mr-1">
              <component :is="col.icon" class="w-4.5 h-4.5 shrink-0" :class="[classes.text]" />
              <div class="min-w-0">
                <h4 class="font-bold text-sm uppercase tracking-wider truncate" :class="[classes.text]">
                  {{ col.title }}
                </h4>
                <p class="text-[10px] text-theme-text-muted leading-tight truncate uppercase tracking-tighter opacity-70">
                  {{ col.subtitle }}
                </p>
              </div>
              <span class="text-xs px-1.5 py-0.25 font-bold rounded shrink-0" :class="[classes.badge]">
                {{ col.tasks.length }}
              </span>
            </div>

            <!-- Controls: Layout Selector (NO collapsing) -->
            <div class="flex items-center shrink-0">
              <!-- Layout Selector Dropdown Menu -->
              <div class="relative flex items-center">
                <button
                  @click.stop="toggleMenu(col.id)"
                  class="text-theme-text-muted hover:text-theme-text-main p-1 hover:bg-theme-card/50 rounded transition-all duration-200 cursor-pointer"
                  :class="{ 'text-theme-text-main bg-theme-card/50': activeMenuColId === col.id }"
                  :title="t('layoutOptions.tooltip')"
                >
                  <MoreHorizontal class="w-4 h-4 shrink-0" />
                </button>

                <!-- Dropdown Panel -->
                <transition
                  enter-active-class="transition duration-100 ease-out"
                  enter-from-class="transform scale-95 opacity-0"
                  enter-to-class="transform scale-100 opacity-100"
                  leave-active-class="transition duration-75 ease-in"
                  leave-from-class="transform scale-100 opacity-100"
                  leave-to-class="transform scale-95 opacity-0"
                >
                  <div
                    v-if="activeMenuColId === col.id"
                    class="absolute right-0 top-full mt-1 bg-theme-card border border-theme-border rounded shadow-lg p-1 flex flex-col gap-1 z-50 min-w-[130px]"
                  >
                    <div
                      class="px-2.5 py-1 text-[9px] font-bold text-theme-text-muted/65 uppercase tracking-wider border-b border-theme-border/30 mb-0.5 select-none"
                    >
                      {{ t('layoutOptions.label') }}
                    </div>
                    <button
                      @click.stop="
                        uiStore.setVirtualColumnLayout('matrix-view', col.id, 'list');
                        closeMenu();
                      "
                      class="flex items-center gap-2.5 px-2.5 py-1.5 text-xs rounded hover:bg-theme-column/50 transition-colors text-left cursor-pointer w-full"
                      :class="[
                        uiStore.getVirtualColumnLayout('matrix-view', col.id, 'grid-3') === 'list'
                          ? 'text-theme-primary font-semibold bg-theme-primary/10'
                          : 'text-theme-text-muted hover:text-theme-text-main',
                      ]"
                    >
                      <List class="w-3.5 h-3.5 shrink-0" />
                      <span>{{ t('layoutOptions.list') }}</span>
                    </button>
                    <button
                      @click.stop="
                        uiStore.setVirtualColumnLayout('matrix-view', col.id, 'grid-2');
                        closeMenu();
                      "
                      class="flex items-center gap-2.5 px-2.5 py-1.5 text-xs rounded hover:bg-theme-column/50 transition-colors text-left cursor-pointer w-full"
                      :class="[
                        uiStore.getVirtualColumnLayout('matrix-view', col.id, 'grid-3') === 'grid-2'
                          ? 'text-theme-primary font-semibold bg-theme-primary/10'
                          : 'text-theme-text-muted hover:text-theme-text-main',
                      ]"
                    >
                      <LayoutGrid class="w-3.5 h-3.5 shrink-0" />
                      <span>{{ t('layoutOptions.grid2') }}</span>
                    </button>
                    <button
                      @click.stop="
                        uiStore.setVirtualColumnLayout('matrix-view', col.id, 'grid-3');
                        closeMenu();
                      "
                      class="flex items-center gap-2.5 px-2.5 py-1.5 text-xs rounded hover:bg-theme-column/50 transition-colors text-left cursor-pointer w-full"
                      :class="[
                        uiStore.getVirtualColumnLayout('matrix-view', col.id, 'grid-3') === 'grid-3'
                          ? 'text-theme-primary font-semibold bg-theme-primary/10'
                          : 'text-theme-text-muted hover:text-theme-text-main',
                      ]"
                    >
                      <Grid class="w-3.5 h-3.5 shrink-0" />
                      <span>{{ t('layoutOptions.grid3') }}</span>
                    </button>
                  </div>
                </transition>
              </div>
            </div>
          </div>
        </template>
      </GenericColumn>
    </div>
  </div>
</template>

<style scoped>
.urgency-slider {
  -webkit-appearance: none;
  appearance: none;
  outline: none;
}

/* Style the Webkit/Blink slider thumb */
.urgency-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 14px;
  height: 14px;
  border-radius: 9999px;
  background: #ffffff;
  border: 2px solid var(--theme-accent, #3b82f6);
  cursor: pointer;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25);
  transition:
    transform 0.15s cubic-bezier(0.4, 0, 0.2, 1),
    border-color 0.15s ease,
    box-shadow 0.15s ease;
}

/* Style the Firefox slider thumb */
.urgency-slider::-moz-range-thumb {
  width: 14px;
  height: 14px;
  border-radius: 9999px;
  background: #ffffff;
  border: 2px solid var(--theme-accent, #3b82f6);
  cursor: pointer;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25);
  transition:
    transform 0.15s cubic-bezier(0.4, 0, 0.2, 1),
    border-color 0.15s ease,
    box-shadow 0.15s ease;
}

/* Hover & Active Effects */
.urgency-slider::-webkit-slider-thumb:hover {
  transform: scale(1.25);
  border-color: var(--theme-accent-hover, #60a5fa);
  box-shadow:
    0 2px 5px rgba(0, 0, 0, 0.3),
    0 0 0 4px var(--theme-ring);
}

.urgency-slider::-moz-range-thumb:hover {
  transform: scale(1.25);
  border-color: var(--theme-accent-hover, #60a5fa);
  box-shadow:
    0 2px 5px rgba(0, 0, 0, 0.3),
    0 0 0 4px var(--theme-ring);
}

.urgency-slider::-webkit-slider-thumb:active {
  transform: scale(1.1);
  box-shadow:
    0 1px 2px rgba(0, 0, 0, 0.2),
    0 0 0 6px var(--theme-ring);
}

.urgency-slider::-moz-range-thumb:active {
  transform: scale(1.1);
  box-shadow:
    0 1px 2px rgba(0, 0, 0, 0.2),
    0 0 0 6px var(--theme-ring);
}
</style>
